### ISSUE TITLE
ImportError: no module named bootstrap

### ISSUE THREAD

**Issue by l4nn1312** [semarie/build-rust#13]
I'm trying to build nightly on OpenBSD 6.6-current but this is the error I recieve
```
Fri Dec 20 23:43:24 PST 2019: starting rustbuild clean
Traceback (most recent call last):
  File "/home/gigavinyl/.gitinstalls/build-rust/build_dir/rustc-beta-src/x.py",
line 10, in <module>
    import bootstrap
ImportError: No module named bootstrap
```

**Comment by semarie** [comment]
without more information, I could only saying that the error is from rust itself.
could you show the whole build output ?

you could also try to remove `build_dir` and `install_dir` to start from a clean state.

**Comment by gigavinyl** [comment]
Hmm tried removing both and still got the error. I can't find build.log but here's more context of the error:
```
error: cannot find attribute `rustc_reservation_impl` in this scope
   --> src/libcore/convert/mod.rs:577:3
    |
577 | #[rustc_reservation_impl = "permitting this impl would forbid us from adding \
    |   ^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: the `#[non_exhaustive]` attribute is an experimental feature
    --> src/libcore/num/mod.rs:5182:1
     |
5182 | #[non_exhaustive]
     | ^^^^^^^^^^^^^^^^^
     |
     = note: for more information, see https://github.com/rust-lang/rust/issues/44109
     = help: add `#![feature(non_exhaustive)]` to the crate attributes to enable

error[E0658]: the `#[non_exhaustive]` attribute is an experimental feature
   --> src/libcore/sync/atomic.rs:232:1

232 | #[non_exhaustive]
    | ^^^^^^^^^^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/44109
    = help: add `#![feature(non_exhaustive)]` to the crate attributes to enable

error[E0522]: definition of an unknown language item: `structural_peq`
   --> src/libcore/marker.rs:152:1
    |
152 | #[lang = "structural_peq"]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^ definition of unknown language item `structural_peq`

error[E0522]: definition of an unknown language item: `structural_teq`
   --> src/libcore/marker.rs:202:1
    |
202 | #[lang = "structural_teq"]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^ definition of unknown language item `structural_teq`

error[E0522]: definition of an unknown language item: `panic_location`
   --> src/libcore/panic.rs:172:1

    | ^^^^^^^^^^^^^^^^^^^^^^^^^^ definition of unknown language item `panic_location`

error[E0119]: conflicting implementations of trait `convert::From<!>` for type `!`:
   --> src/libcore/convert/mod.rs:579:1
    |
564 | impl<T> From<T> for T {
    | --------------------- first implementation here
...
579 | impl<T> From<!> for T {
    | ^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `!`

error: aborting due to 7 previous errors

Some errors have detailed explanations: E0119, E0522, E0658.
For more information about an error, try `rustc --explain E0119`.
error: could not compile `core`.
warning: build failed, waiting for other jobs to finish...
error: build failed
command did not execute successfully: "/usr/local/bin/cargo" "build" "-Zconfig-profile" "--target" "x86_64-unknown-openbsd" "-Zbinary-dep-depinfo" "-j" "2" "--release" "--frozen" "--features" "panic-unwind backtrace compiler-builtins-c" "--
manifest-path" "/home/gigavinyl/.gitinstalls/build-rust/build_dir/rustc-beta-src/src/libtest/Cargo.toml" "--message-format" "json-render-diagnostics"
expected success, got: exit code: 101
Traceback (most recent call last):
  File "/home/gigavinyl/.gitinstalls/build-rust/build_dir/rustc-beta-src/x.py",
line 11, in <module>
    bootstrap.main()
  File "/home/gigavinyl/.gitinstalls/build-rust/build_dir/rustc-beta-src/src/bootstrap/bootstrap.py", line 912, in main
    bootstrap(help_triggered)
  File "/home/gigavinyl/.gitinstalls/build-rust/build_dir/rustc-beta-src/src/bootstrap/bootstrap.py", line 898, in bootstrap
    run(args, env=env, verbose=build.verbose)
  File "/home/gigavinyl/.gitinstalls/build-rust/build_dir/rustc-beta-src/src/bootstrap/bootstrap.py", line 141, in run
    raise RuntimeError(err)
RuntimeError: failed to run: /home/gigavinyl/.gitinstalls/build-rust/build_dir/build/bootstrap/debug/bootstrap dist --jobs=2
Sun Dec 22 01:11:55 PST 2019: task not finished: see build.log for detail
Sun Dec 22 01:11:55 PST 2019: task not finished: see build.log for detail
~/.gitinstalls/build-rust >>> ./build.sh nightly

**Comment by semarie** [comment]
`build.log` should be at `/home/gigavinyl/.gitinstalls/build-rust/install_dir/beta/build.log`.

but with more context, the problem seems your are building rust 1.41.0 with rust 1.39.0, and it isn't a supported configuration for rust compiler.

the problem is 1.40.0 isn't commited in ports tree for now (it will be soon).

**Comment by gigavinyl** [comment]
Darn :/ so am I stuck until the port comes out or is there a way to bootstrap a newer rust version?

**Comment by semarie** [comment]
I just commited it on cvs. so you should be able to update your ports tree soon (once mirrors update) and build a rust 1.40.0 from it. Once done, you will be able to build beta (and next nightly).

**Comment by gigavinyl** [comment]
Awesome thanks!

**Comment by gigavinyl** [comment]
Darn :/ I get a compilation error on the new port
```
warning: build failed, waiting for other jobs to finish...
error: build failed
command did not execute successfully: "/usr/ports/pobj/rust-1.40.0/rustc-bootstrap-amd64-1.40.0-20191217/bin/cargo" "build" "-Zconfig-profile" "--target" "x86_64-unknown-openbsd" "-Zbinary-dep-depinfo" "-j" "2" "-v" "--release" "--frozen" "--features" "panic-unwind backtrace compiler-builtins-c" "--manifest-path" "/usr/ports/pobj/rust-1.40.0/rustc-1.40.0-src/src/libtest/Cargo.toml" "--message-format" "json-render-diagnostics"
expected success, got: exit code: 101
Traceback (most recent call last):
  File "/usr/ports/pobj/rust-1.40.0/rustc-1.40.0-src/x.py", line 11, in <module>
    bootstrap.main()
  File "/usr/ports/pobj/rust-1.40.0/rustc-1.40.0-src/src/bootstrap/bootstrap.py", line 898, in main
    bootstrap(help_triggered)
  File "/usr/ports/pobj/rust-1.40.0/rustc-1.40.0-src/src/bootstrap/bootstrap.py", line 884, in bootstrap
    run(args, env=env, verbose=build.verbose)
  File "/usr/ports/pobj/rust-1.40.0/rustc-1.40.0-src/src/bootstrap/bootstrap.py", line 141, in run
    raise RuntimeError(err)
RuntimeError: failed to run: /usr/ports/pobj/rust-1.40.0/build-amd64/build/bootstrap/debug/bootstrap dist --jobs=2 src/libstd src/librustc cargo clippy rustfmt
```

**Comment by semarie** [comment]
please include the whole build log. this part is useless: it just say the build failed.

```
$ cd /usr/ports/lang/rust && make 2>&1 | /usr/ports/infrastructure/bin/portslogger path/to/logdir
```

and attach the log file related to rust.

**Comment by semarie** [comment]
closing due to inactivity. please reopen with more information.
