### ISSUE TITLE
Build fails with OpenBSD -CURRENT (ccache: not found)

### ISSUE THREAD

**Issue by AaronM04** [semarie/build-rust#16]
I ran this with -CURRENT (patched as of today, 2020-07-15).
Rust was installed with pkg_add. Version: `1.44.1`.

```
$ SUDO=doas time ./build.sh nightly
Wed Jul 15 11:40:51 PDT 2020: target: nightly - x86_64-unknown-openbsd
Wed Jul 15 11:40:51 PDT 2020: fetching (cache hit): rustc-nightly-src.tar.gz
Wed Jul 15 11:40:51 PDT 2020: fetching (cache hit): rustc-nightly-src.tar.gz
Wed Jul 15 11:40:51 PDT 2020: removing /home/x/build-rust/build_dir/rustc-nightly-src
Wed Jul 15 11:41:22 PDT 2020: extracting rustc-nightly-src.tar.gz
Wed Jul 15 11:42:41 PDT 2020: patching nightly
patching: bootstrap: pass optimization flags
patching: openssl-sys: libressl in -current isn't explicitly supported
Wed Jul 15 11:42:42 PDT 2020: fetching (cache hit): rustc-beta-src.tar.gz
Wed Jul 15 11:42:43 PDT 2020: fetching (cache hit): rustc-beta-src.tar.gz
Wed Jul 15 11:42:43 PDT 2020: removing /home/x/build-rust/build_dir/rustc-beta-src
Wed Jul 15 11:43:10 PDT 2020: extracting rustc-beta-src.tar.gz
Wed Jul 15 11:44:13 PDT 2020: patching beta
patching: bootstrap: pass optimization flags
patching: openssl-sys: libressl in -current isn't explicitly supported
Wed Jul 15 11:44:13 PDT 2020: installing rustfmt-stable (from ports)
doas (x@redacted) password: 
quirks-3.383 signed on 2020-07-13T20:22:41Z
Wed Jul 15 11:44:23 PDT 2020: info: building: 1.45.0-beta.4 (e99e6422a 2020-07-13)
Wed Jul 15 11:44:23 PDT 2020: info: required stage0:
	date: 2020-06-04
	rustc: 1.44.0
	cargo: 0.45.0
Wed Jul 15 11:44:23 PDT 2020: info: rustc -vV
	rustc 1.44.1
	binary: rustc
	commit-hash: unknown
	commit-date: unknown
	host: x86_64-unknown-openbsd
	release: 1.44.1
	LLVM version: 8.0
Wed Jul 15 11:44:24 PDT 2020: info: cargo -vV
	cargo 1.44.1
	release: 1.44.1
Wed Jul 15 11:44:24 PDT 2020: info: rustfmt -V
	rustfmt 1.4.16-
Wed Jul 15 11:44:24 PDT 2020: starting rustbuild dist --jobs=2
running: /usr/local/bin/cargo build --manifest-path /home/x/build-rust/build_dir/rustc-beta-src/src/bootstrap/Cargo.toml --frozen
   Compiling proc-macro2 v1.0.3
   Compiling unicode-xid v0.2.0
   Compiling memchr v2.3.3
error: linking with `cc` failed: exit code: 127
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/usr/local/lib/rustlib/x86_64-unknown-openbsd/lib" "/home/x/build-rust/build_dir/build/bootstrap/debug/build/memchr-9fd9abd8b31a75d9/build_script_build-9fd9abd8b31a75d9.build_script_build.bkjus4ps-cgu.0.rcgu.o" "/home/x/build-rust/build_dir/build/bootstrap/debug/build/memchr-9fd9abd8b31a75d9/build_script_build-9fd9abd8b31a75d9.build_script_build.bkjus4ps-cgu.1.rcgu.o" "/home/x/build-rust/build_dir/build/bootstrap/debug/build/memchr-9fd9abd8b31a75d9/build_script_build-9fd9abd8b31a75d9.build_script_build.bkjus4ps-cgu.10.rcgu.o" "/home/x/build-rust/build_dir/build/bootstrap/debug/build/memchr-9fd9abd8b31a75d9/build_script_build-9fd9abd8b31a75d9.build_script_build.bkjus4ps-cgu.11.rcgu.o" "/home/x/build-rust/build_dir/build/bootstrap/debug/build/memchr-9fd9abd8b31a75d9/build_script_build-9fd9abd8b31a75d9.build_script_build.bkjus4ps-cgu.12.rcgu.o" "/home/x/build-rust/build_dir/build/bootstrap/debug/build/memchr-9fd9abd8b31a75d9/build_script_build-9fd9abd8b31a75d9.build_script_build.bkjus4ps-cgu.13.rcgu.o" "/home/x/build-rust/build_dir/build/bootstrap/debug/build/memchr-9fd9abd8b31a75d9/build_script_build-9fd9abd8b31a75d9.build_script_build.bkjus4ps-cgu.14.rcgu.o" "/home/x/build-rust/build_dir/build/bootstrap/debug/build/memchr-9fd9abd8b31a75d9/build_script_build-9fd9abd8b31a75d9.build_script_build.bkjus4ps-cgu.15.rcgu.o" "/home/x/build-rust/build_dir/build/bootstrap/debug/build/memchr-9fd9abd8b31a75d9/build_script_build-9fd9abd8b31a75d9.build_script_build.bkjus4ps-cgu.2.rcgu.o" "/home/x/build-rust/build_dir/build/bootstrap/debug/build/memchr-9fd9abd8b31a75d9/build_script_build-9fd9abd8b31a75d9.build_script_build.bkjus4ps-cgu.3.rcgu.o" "/home/x/build-rust/build_dir/build/bootstrap/debug/build/memchr-9fd9abd8b31a75d9/build_script_build-9fd9abd8b31a75d9.build_script_build.bkjus4ps-cgu.4.rcgu.o" "/home/x/build-rust/build_dir/build/bootstrap/debug/build/memchr-9fd9abd8b31a75d9/build_script_build-9fd9abd8b31a75d9.build_script_build.bkjus4ps-cgu.5.rcgu.o" "/home/x/build-rust/build_dir/build/bootstrap/debug/build/memchr-9fd9abd8b31a75d9/build_script_build-9fd9abd8b31a75d9.build_script_build.bkjus4ps-cgu.6.rcgu.o" "/home/x/build-rust/build_dir/build/bootstrap/debug/build/memchr-9fd9abd8b31a75d9/build_script_build-9fd9abd8b31a75d9.build_script_build.bkjus4ps-cgu.7.rcgu.o" "/home/x/build-rust/build_dir/build/bootstrap/debug/build/memchr-9fd9abd8b31a75d9/build_script_build-9fd9abd8b31a75d9.build_script_build.bkjus4ps-cgu.8.rcgu.o" "/home/x/build-rust/build_dir/build/bootstrap/debug/build/memchr-9fd9abd8b31a75d9/build_script_build-9fd9abd8b31a75d9.build_script_build.bkjus4ps-cgu.9.rcgu.o" "-o" "/home/x/build-rust/build_dir/build/bootstrap/debug/build/memchr-9fd9abd8b31a75d9/build_script_build-9fd9abd8b31a75d9" "/home/x/build-rust/build_dir/build/bootstrap/debug/build/memchr-9fd9abd8b31a75d9/build_script_build-9fd9abd8b31a75d9.4t9vtp45mbsq516a.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs" "-L" "/home/x/build-rust/build_dir/build/bootstrap/debug/deps" "-L" "/usr/local/lib/rustlib/x86_64-unknown-openbsd/lib" "-Wl,--start-group" "-Wl,-Bstatic" "/usr/local/lib/rustlib/x86_64-unknown-openbsd/lib/libstd-d33aee1508eaf113.rlib" "/usr/local/lib/rustlib/x86_64-unknown-openbsd/lib/libpanic_unwind-d33aee1508eaf10b.rlib" "/usr/local/lib/rustlib/x86_64-unknown-openbsd/lib/libhashbrown-d33aee1508eaf108.rlib" "/usr/local/lib/rustlib/x86_64-unknown-openbsd/lib/librustc_std_workspace_alloc-d33aee1508eaf110.rlib" "/usr/local/lib/rustlib/x86_64-unknown-openbsd/lib/libbacktrace-d33aee1508eaf102.rlib" "/usr/local/lib/rustlib/x86_64-unknown-openbsd/lib/libbacktrace_sys-d33aee1508eaf103.rlib" "/usr/local/lib/rustlib/x86_64-unknown-openbsd/lib/librustc_demangle-d33aee1508eaf10d.rlib" "/usr/local/lib/rustlib/x86_64-unknown-openbsd/lib/libunwind-d33aee1508eaf117.rlib" "/usr/local/lib/rustlib/x86_64-unknown-openbsd/lib/libcfg_if-d33aee1508eaf104.rlib" "/usr/local/lib/rustlib/x86_64-unknown-openbsd/lib/liblibc-d33aee1508eaf109.rlib" "/usr/local/lib/rustlib/x86_64-unknown-openbsd/lib/liballoc-d33aee1508eaf101.rlib" "/usr/local/lib/rustlib/x86_64-unknown-openbsd/lib/librustc_std_workspace_core-d33aee1508eaf111.rlib" "/usr/local/lib/rustlib/x86_64-unknown-openbsd/lib/libcore-d33aee1508eaf106.rlib" "-Wl,--end-group" "/usr/local/lib/rustlib/x86_64-unknown-openbsd/lib/libcompiler_builtins-d33aee1508eaf105.rlib" "-Wl,-Bdynamic" "-lpthread" "-lc++abi" "-lc" "-lm" "-lutil" "-lcompiler_rt"
  = note: /home/x/build-rust/build_dir/bin/cc[2]: ccache: not found
          

error: aborting due to previous error

error: could not compile `memchr`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: linking with `cc` failed: exit code: 127
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/usr/local/lib/rustlib/x86_64-unknown-openbsd/lib" "/home/x/build-rust/build_dir/build/bootstrap/debug/build/proc-macro2-cb02a9405b37a89a/build_script_build-cb02a9405b37a89a.build_script_build.6i8cc2zr-cgu.0.rcgu.o" "/home/x/build-rust/build_dir/build/bootstrap/debug/build/proc-macro2-cb02a9405b37a89a/build_script_build-cb02a9405b37a89a.build_script_build.6i8cc2zr-cgu.1.rcgu.o" "/home/x/build-rust/build_dir/build/bootstrap/debug/build/proc-macro2-cb02a9405b37a89a/build_script_build-cb02a9405b37a89a.build_script_build.6i8cc2zr-cgu.10.rcgu.o" "/home/x/build-rust/build_dir/build/bootstrap/debug/build/proc-macro2-cb02a9405b37a89a/build_script_build-cb02a9405b37a89a.build_script_build.6i8cc2zr-cgu.11.rcgu.o" "/home/x/build-rust/build_dir/build/bootstrap/debug/build/proc-macro2-cb02a9405b37a89a/build_script_build-cb02a9405b37a89a.build_script_build.6i8cc2zr-cgu.12.rcgu.o" "/home/x/build-rust/build_dir/build/bootstrap/debug/build/proc-macro2-cb02a9405b37a89a/build_script_build-cb02a9405b37a89a.build_script_build.6i8cc2zr-cgu.13.rcgu.o" "/home/x/build-rust/build_dir/build/bootstrap/debug/build/proc-macro2-cb02a9405b37a89a/build_script_build-cb02a9405b37a89a.build_script_build.6i8cc2zr-cgu.14.rcgu.o" "/home/x/build-rust/build_dir/build/bootstrap/debug/build/proc-macro2-cb02a9405b37a89a/build_script_build-cb02a9405b37a89a.build_script_build.6i8cc2zr-cgu.15.rcgu.o" "/home/x/build-rust/build_dir/build/bootstrap/debug/build/proc-macro2-cb02a9405b37a89a/build_script_build-cb02a9405b37a89a.build_script_build.6i8cc2zr-cgu.2.rcgu.o" "/home/x/build-rust/build_dir/build/bootstrap/debug/build/proc-macro2-cb02a9405b37a89a/build_script_build-cb02a9405b37a89a.build_script_build.6i8cc2zr-cgu.3.rcgu.o" "/home/x/build-rust/build_dir/build/bootstrap/debug/build/proc-macro2-cb02a9405b37a89a/build_script_build-cb02a9405b37a89a.build_script_build.6i8cc2zr-cgu.4.rcgu.o" "/home/x/build-rust/build_dir/build/bootstrap/debug/build/proc-macro2-cb02a9405b37a89a/build_script_build-cb02a9405b37a89a.build_script_build.6i8cc2zr-cgu.5.rcgu.o" "/home/x/build-rust/build_dir/build/bootstrap/debug/build/proc-macro2-cb02a9405b37a89a/build_script_build-cb02a9405b37a89a.build_script_build.6i8cc2zr-cgu.6.rcgu.o" "/home/x/build-rust/build_dir/build/bootstrap/debug/build/proc-macro2-cb02a9405b37a89a/build_script_build-cb02a9405b37a89a.build_script_build.6i8cc2zr-cgu.7.rcgu.o" "/home/x/build-rust/build_dir/build/bootstrap/debug/build/proc-macro2-cb02a9405b37a89a/build_script_build-cb02a9405b37a89a.build_script_build.6i8cc2zr-cgu.8.rcgu.o" "/home/x/build-rust/build_dir/build/bootstrap/debug/build/proc-macro2-cb02a9405b37a89a/build_script_build-cb02a9405b37a89a.build_script_build.6i8cc2zr-cgu.9.rcgu.o" "-o" "/home/x/build-rust/build_dir/build/bootstrap/debug/build/proc-macro2-cb02a9405b37a89a/build_script_build-cb02a9405b37a89a" "/home/x/build-rust/build_dir/build/bootstrap/debug/build/proc-macro2-cb02a9405b37a89a/build_script_build-cb02a9405b37a89a.4qwz3jr4jqqng61f.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs" "-L" "/home/x/build-rust/build_dir/build/bootstrap/debug/deps" "-L" "/usr/local/lib/rustlib/x86_64-unknown-openbsd/lib" "-Wl,--start-group" "-Wl,-Bstatic" "/usr/local/lib/rustlib/x86_64-unknown-openbsd/lib/libstd-d33aee1508eaf113.rlib" "/usr/local/lib/rustlib/x86_64-unknown-openbsd/lib/libpanic_unwind-d33aee1508eaf10b.rlib" "/usr/local/lib/rustlib/x86_64-unknown-openbsd/lib/libhashbrown-d33aee1508eaf108.rlib" "/usr/local/lib/rustlib/x86_64-unknown-openbsd/lib/librustc_std_workspace_alloc-d33aee1508eaf110.rlib" "/usr/local/lib/rustlib/x86_64-unknown-openbsd/lib/libbacktrace-d33aee1508eaf102.rlib" "/usr/local/lib/rustlib/x86_64-unknown-openbsd/lib/libbacktrace_sys-d33aee1508eaf103.rlib" "/usr/local/lib/rustlib/x86_64-unknown-openbsd/lib/librustc_demangle-d33aee1508eaf10d.rlib" "/usr/local/lib/rustlib/x86_64-unknown-openbsd/lib/libunwind-d33aee1508eaf117.rlib" "/usr/local/lib/rustlib/x86_64-unknown-openbsd/lib/libcfg_if-d33aee1508eaf104.rlib" "/usr/local/lib/rustlib/x86_64-unknown-openbsd/lib/liblibc-d33aee1508eaf109.rlib" "/usr/local/lib/rustlib/x86_64-unknown-openbsd/lib/liballoc-d33aee1508eaf101.rlib" "/usr/local/lib/rustlib/x86_64-unknown-openbsd/lib/librustc_std_workspace_core-d33aee1508eaf111.rlib" "/usr/local/lib/rustlib/x86_64-unknown-openbsd/lib/libcore-d33aee1508eaf106.rlib" "-Wl,--end-group" "/usr/local/lib/rustlib/x86_64-unknown-openbsd/lib/libcompiler_builtins-d33aee1508eaf105.rlib" "-Wl,-Bdynamic" "-lpthread" "-lc++abi" "-lc" "-lm" "-lutil" "-lcompiler_rt"
  = note: /home/x/build-rust/build_dir/bin/cc[2]: ccache: not found
          

error: aborting due to previous error

error: could not compile `proc-macro2`.

To learn more, run the command again with --verbose.
Traceback (most recent call last):
  File "/home/x/build-rust/build_dir/rustc-beta-src/x.py", line 11, in <module>
    bootstrap.main()
  File "/home/x/build-rust/build_dir/rustc-beta-src/src/bootstrap/bootstrap.py", line 970, in main
    bootstrap(help_triggered)
  File "/home/x/build-rust/build_dir/rustc-beta-src/src/bootstrap/bootstrap.py", line 939, in bootstrap
    build.build_bootstrap()
  File "/home/x/build-rust/build_dir/rustc-beta-src/src/bootstrap/bootstrap.py", line 727, in build_bootstrap
    run(args, env=env, verbose=self.verbose)
  File "/home/x/build-rust/build_dir/rustc-beta-src/src/bootstrap/bootstrap.py", line 143, in run
    raise RuntimeError(err)
RuntimeError: failed to run: /usr/local/bin/cargo build --manifest-path /home/x/build-rust/build_dir/rustc-beta-src/src/bootstrap/Cargo.toml --frozen
Wed Jul 15 11:44:26 PDT 2020: task not finished: see build.log for detail
Wed Jul 15 11:44:26 PDT 2020: task not finished: see build.log for detail
      215.12 real        11.72 user        68.07 sys
```

**Comment by AaronM04** [comment]
I just noticed `ccache` is a package, so I'm installing it and retrying. I will update this issue with the results.

**Comment by AaronM04** [comment]
Closing this as I didn't read the instructions carefully and so did not run the `init` subcommand beforehand.
