### ISSUE TITLE
`build.sh beta build` tries to git update vendored dependency

### ISSUE THREAD

**Issue by bugabinga** [semarie/build-rust#9]
Hi

It seems this issue is supposed to be [fixed upstream](https://github.com/rust-lang/rust/issues/42719).
I am using _-stable_.
Should `build-rust` even work with 6.3?

```sh
 oliver:130$ ./build.sh beta build                                                                                                      
Tue Jul  3 20:24:54 CEST 2018: target: beta - x86_64-unknown-openbsd
Tue Jul  3 20:24:54 CEST 2018: starting rustbuild dist --jobs=2
running: /usr/local/bin/cargo build --manifest-path /home/oliver/Workspace/rustlang/build-rust/build_dir/rustc-beta-src/src/bootstrap/Cargo.toml --frozen
warning: unused manifest key: package.autobenches
warning: unused manifest key: package.autotests
warning: unused manifest key: package.autobenches
warning: unused manifest key: package.autotests
    Updating git repository `https://github.com/rust-lang-nursery/rustfmt`
error: failed to load source for a dependency on `rustfmt-nightly`

Caused by:
  Unable to update https://github.com/rust-lang-nursery/rustfmt?rev=f3906267#f3906267

Caused by:
  failed to fetch into /home/oliver/Workspace/rustlang/build-rust/install_dir/crates/git/db/rustfmt-5390e0ead582d971

Caused by:
  attempting to update a git repository, but --frozen was specified
Traceback (most recent call last):
  File "/home/oliver/Workspace/rustlang/build-rust/build_dir/rustc-beta-src/x.py", line 20, in <module>
    bootstrap.main()
  File "/home/oliver/Workspace/rustlang/build-rust/build_dir/rustc-beta-src/src/bootstrap/bootstrap.py", line 827, in main
    bootstrap(help_triggered)
  File "/home/oliver/Workspace/rustlang/build-rust/build_dir/rustc-beta-src/src/bootstrap/bootstrap.py", line 806, in bootstrap
    build.build_bootstrap()
  File "/home/oliver/Workspace/rustlang/build-rust/build_dir/rustc-beta-src/src/bootstrap/bootstrap.py", line 633, in build_bootstrap
    run(args, env=env, verbose=self.verbose)
  File "/home/oliver/Workspace/rustlang/build-rust/build_dir/rustc-beta-src/src/bootstrap/bootstrap.py", line 148, in run
    raise RuntimeError(err)
RuntimeError: failed to run: /usr/local/bin/cargo build --manifest-path /home/oliver/Workspace/rustlang/build-rust/build_dir/rustc-beta-src/src/bootstrap/Cargo.toml --frozen
```

@semarie Unless you think this issue is a new issue, I will close this soon, ok?

**Comment by bugabinga** [comment]
Mh, you've already hit this: https://github.com/rust-lang/rust/pull/51407

**Comment by semarie** [comment]
in order to build the current beta (1.28-beta), you need a rustc version 1.27.0.
so you can't use this tool from openbsd-stable to build beta or nightly.

you could try to checkout the port lang/rust from openbsd-current, and try to build it first. I think stable isn't too old to use the binary bootstrap from it. but it is an unsupported configuration.

else you should build each rust release from 1.24.0 (version in openbsd-stable) to 1.27.0
